### ISSUE TITLE
Inlined functions in function level profiling

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#2118]
### Which components does the task require to be changed? (think hard pls)

other (describe below)

### Description

Blocked by #1725 
Mapping from Scarb 
```toml
[cairo]
unstable-add-statements-functions-debug-info = true
```
are needed for this
