### ISSUE TITLE
Design a mechanism for easier backtrace usage in snforge

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2867]
### Current State

Currently, to use backtrace, 
```toml
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
```
lines must be added to `Scarb.toml` file. Adding these lines slows down compilation so it is not desired to have them defined in Scarb.toml at all times.

### Objective

Design a mechanism for easier backtrace usage in snforge

### Additional Context

There are many ideas on how this could be implemented: Leverage scarb profiles, after #1619 is implemented, by for example creating different profiles when creating a forge profile or even during runtime. Other possible solution would be to allow configuring these flags in scarb as an cli option, env var or similar and settings them through forge accordingly.
