### ISSUE TITLE
Asdf doesn't install foundry from `.tool-versions`

### ISSUE THREAD

**Issue by franciszekjob** [foundry-rs/starknet-foundry#3295]
### Current State

Asdf doesn't install `starknet foundry` from `.tool-versions` file

Repro steps:
1. Put `.tool-versions` file with `starknet foundry` inside
2. Add following step to CI
```
      - name: Install asdf & tools
        uses: asdf-vm/actions/setup@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
        with:
          asdf_version: 0.16.7
```
3. Check if `starknet foundry` is installed

Full discussion on telegram:

### Objective

Asdf doesn't install foundry from `.tool-versions`

### Additional Context

Full discussion on telegram: https://t.me/c/1788692421/2450
