### ISSUE TITLE
Support for declare calls in multicalls

### ISSUE THREAD

**Issue by tiagofneto** [foundry-rs/starknet-foundry#789]
### Which component is your feature related to?

Cast

### Summary
I propose adding support for declare calls within multicalls. This feature would allow deploy calls to reference previously declared class hashes by using a parameter, such as `id`, defined in the declare call. The primary benefit is to streamline the deployment process by reducing manual steps.

### Details
Currently, declaring a contract requires a manual process that involves declaring the contract, and then updating the TOML file with the new class hash. This is time consuming and a tedious process.

By supporting declare calls in multicalls, we can automate this process. If a contract is already declared, the multicall should still proceed successfully. To aid in debugging, warnings could be sent to _stderr_ indicating which contracts were already declared.

### Example
Here is what a multicall with `declare` calls support could look like:

```toml
[[call]]
call_type = "declare"
contract_name = "MyContract"
id = "declared_contract"

[[call]]
call_type = "deploy"
class_hash = "declared_contract"
inputs = []
unique = false
```
